### ISSUE TITLE
PassthroughConnection.close after PassthroughServer.stop throws AssertionError instead of IOException

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-apis#102]
If `PassthroughConnection.close()` is called after `PassthroughServer.stop()` is called, an `AssertionError` is thrown instead of an `IOException` -- should be an `IOException`.

----
Sample stack trace:

````
java.lang.AssertionError: Case must be true
    at org.terracotta.passthrough.Assert.assertTrue(Assert.java:41)
    at org.terracotta.passthrough.PassthroughServerProcess.sendMessageToServer(PassthroughServerProcess.java:316)
    at org.terracotta.passthrough.PassthroughConnectionState.createAndSend(PassthroughConnectionState.java:79)
    at org.terracotta.passthrough.PassthroughConnectionState.sendNormal(PassthroughConnectionState.java:65)
    at org.terracotta.passthrough.PassthroughConnection.invokeAndWait(PassthroughConnection.java:138)
    at org.terracotta.passthrough.PassthroughConnection.sendUnexpectedCloseMessage(PassthroughConnection.java:367)
    at org.terracotta.passthrough.PassthroughConnection.close(PassthroughConnection.java:324)
    at org.ehcache.clustered.client.internal.UnitTestConnectionService.remove(UnitTestConnectionService.java:169)
    at org.ehcache.clustered.client.internal.UnitTestConnectionService.remove(UnitTestConnectionService.java:189)
    at org.ehcache.clustered.client.internal.service.DefaultClusteringServiceTest.removePassthroughServer(DefaultClusteringServiceTest.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:364)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
````

**Comment by jd0-sag** [comment]
I am testing a change to this, on our existing tests.

This case probably shouldn't throw an exception since it is just closing down the local side of the connection.

Something we still need to define is the correct exception to throw in cases related to this.  Currently, the one used through much of the code is "IllegalStateException", which is not as specific as I would like.

IOException isn't the obvious case, either, since we may want this to be a non-checked exception (since most of the underlying machinery handles the actual IO layer - this is more about the logical meaning we want to expose).

Ideally, the exception would be the same for all of:  close() a closed connection, send a message to a non-existent server, get() on a future while the underlying connection is closed.

**Comment by jd0-sag** [comment]
Specifically, the changes I am testing at are in:  https://github.com/jd0-sag/terracotta-apis/tree/illegal_state_exception

**Comment by cljohnso** [comment]
`PassthroughConnection` implements `Closeable` which declares a `close()` method that throws `IOException`.  You can certainly choose _not_ to throw that exception but that's the usual choice for `close`.
